import { Platform, StyleSheet, Dimensions } from 'react-native';
import { Constants } from '../common';
export const { width, height } = Dimensions.get('window');
const leftPopup = width - (width - 80);
const IS_IPHONE_X = height === 812 || height === 896;
const marginMinusSmall = -50;
const marginMinusBig = -60;
const fontSmall = 14;
const fontMedium = 16;
const fontBig = 18;
const fontLarge = 20;
const fontXLarge = 24;
const whiteColor = '#FFF';
const fontRegular = 'Roboto-Regular';
const fontSemiBold = 'Roboto-Regular';
const fontBold = 'Roboto-Regular';
const fontBolder = 'Roboto-Regular';
//export const { fontBold } = "Gotham-Black";
const styles = StyleSheet.create({
  fontBook: {
    //fontFamily:fontRegular
  },
  splashBg: {
    width: width,
    height: height,
    resizeMode: 'stretch',
    flex: 1,
    backgroundColor: '#000',
  },
  splashInner: {
    flex: 1,
  },
  splashIndicator: {
    width: '100%',
    paddingVertical: 20,
  },
  splashLogo: {
    width: width / 3,
    height: height / 8,
    resizeMode: 'contain',
  },
  splashLogoText: {
    width: width / 1.6,
    height: 50,
    resizeMode: 'contain',
    marginVertical: 10,
  },
  splashLoadingText: {
    color: '#757d83',
    fontSize: fontBig,
    paddingVertical: 15,
    textAlign: 'center',
  },
  mainBg: {
    width: width,
    height: height,
    resizeMode: 'stretch',
    flex: 1,
    backgroundColor: '#ef795d',
  },
  mainLogo: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  forgotLogo: {
    width: Platform.OS == 'ios' ? width / 1.5 : width / 1.9,
    height: 150,
    resizeMode: 'contain',
  },
  labelContainer: {
    flexDirection: 'row',
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 5,
    paddingHorizontal: 15,
    marginBottom: 25,
    borderBottomWidth: 0.8,
    borderColor: '#c1c2c4',
  },
  registerIcons: {
    marginHorizontal: 5,
    width: 20,
    height: 22,
    fontSize: 16,
    color: '#CCCCCC',
  },
  formIcons: {
    marginHorizontal: 5,
    width: 25,
    height: 25,
    fontSize: 20,
    color: '#CCCCCC',
  },
  listIcons: {
    width: 18,
    height: 18,
    fontSize: 14,
    color: '#45add7',
  },
  labelForm: {
    fontSize: fontSmall,
    color: '#4b4b4b',
    paddingHorizontal: 15,
    fontWeight: Platform.OS == 'ios' ? '700' : '500',
    paddingVertical: 5,
  },
  formIconsCont: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  formInput: {
    width: '100%',
    height: 45,
    fontSize: 14,
    color: '#1D2733',
    fontWeight: Platform.OS == 'ios' ? '500' : '200',
    //textAlignVertical: "top"
  },
  formInputText: {
    width: '100%',
    fontSize: 14,
    color: '#1D2733',
    //fontFamily:fontRegular,
    paddingVertical: 15,
    fontWeight: Platform.OS == 'ios' ? '500' : '200',
  },
  phoneText: {
    height: 45,
    fontSize: 14,
    color: '#1D2733',
    fontWeight: '500',
    //fontFamily:fontRegular,
  },
  pinInput: {
    width: '22%',
    height: 45,
    fontSize: 14,
    marginLeft: 5,
    marginRight: 5,
    textAlign: 'center',
    color: whiteColor,
    borderBottomWidth: 2,
    borderBottomColor: whiteColor,
    fontWeight: 'bold',
    //fontFamily:fontRegular,
  },
  loginText: {
    paddingVertical: 5,
    color: '#999B9F',
    fontSize: 13,
    //fontFamily: fontRegular,
    paddingHorizontal: 25,
    lineHeight: 20,
  },
  dashboardMainView: {
    flex: 1,
    backgroundColor: whiteColor,
  },
  dashboardContainerView: {
    flex: 1,
    backgroundColor: whiteColor,
  },
  drawerContainer: {
    flex: 1,
    backgroundColor: '#fafcfd',
    overflow: 'hidden',
  },
  bottomBar: {
    height: IS_IPHONE_X === true ? 80 : 70,
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 10,
    shadowOpacity: 0.3,
    borderTopWidth: Platform.OS == 'ios' ? 0 : 0.2,
    borderColor: '#a5a4a4',
    elevation: 4,
    paddingBottom: IS_IPHONE_X === true ? 10 : 0,
  },
  footerButtons: {
    flex: 1,
  },
  bottomBarIcons: {
    height: 22,
    width: 22,
    resizeMode: 'contain',
  },
  bottomBarIconBig: {
    height: 50,
    width: 90,
  },
  bannerCont: {
    width: '100%',
    height: height / 6,
    backgroundColor: 'grey',
    borderRadius: 20,
    overflow: 'hidden',
  },
  bannerImage: {
    width: null,
    height: height / 6,
    resizeMode: 'cover',
  },
  detailBannerMainCont: {
    width: '100%',
    height: 160,
    backgroundColor: whiteColor,
    borderRadius: 10,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 3,
    shadowOpacity: 0.3,
  },
  detailBannerCont: {
    width: '100%',
    height: 160,
    backgroundColor: whiteColor,
    borderRadius: 10,
    overflow: 'hidden',
  },
  detailBannerImage: {
    width: null,
    height: 160,
    resizeMode: 'cover',
  },
  detailBannerInner: {
    backgroundColor: whiteColor,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: whiteColor,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    marginTop: -50,
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  bannerDetailIconContInner: {
    width: 50,
    height: 50,
    overflow: 'hidden',
    borderRadius: 25,
  },
  bannerDetailIconContInner2: {
    width: 50,
    height: 50,
  },
  bannerDetailIconImage: {
    width: 50,
    height: 50,
    resizeMode: 'stretch',
  },
  bannerDetailIconCont: {
    width: 50,
  },
  detailInnerIcons: {
    width: 40,
    height: 40,
    marginLeft: 2,
  },
  detailInnerIconsImage: {
    width: 40,
    height: 40,
  },
  gymHeading: {
    color: '#2d2d2f',
    fontSize: fontSmall,
    fontWeight: 'bold',
  },
  marginTopMinus: {
    marginTop: IS_IPHONE_X === true ? marginMinusBig : marginMinusSmall,
  },
  homeHeading: {
    fontSize: fontBig,
    color: '#45add7',
    //fontFamily: fontBold,
    paddingVertical: 5,
  },
  homeHeadingUnSelected: {
    fontSize: fontBig,
    color: '#8a93a5',
    //fontFamily:fontRegular
  },
  homeInnerText: {
    fontSize: fontSmall,
    color: '#a8a8a8',
    paddingVertical: 5,
    //fontFamily: fontRegular
  },
  cardView: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: whiteColor,
    paddingHorizontal: 20,
    paddingVertical: 20,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    shadowOpacity: 0.2,
  },
  aboutText: {
    color: '#4b4b4b',
    fontSize: fontSmall,
    lineHeight: 23,
    paddingVertical: 20,
    textAlign: 'justify',
  },
  editImageCont: {
    width: 124,
    height: 124,
    borderRadius: 62,
    borderWidth: 4,
    borderColor: '#fcb828',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fcb828',
  },
  editImage: {
    width: 116,
    height: 116,
    resizeMode: 'cover',
    borderRadius: 58,
  },
  cameraIconCont: {
    backgroundColor: '#fcb828',
    width: 40,
    height: 40,
    borderRadius: 20,
    position: 'absolute',
    right: -5,
    bottom: -5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraIconImage: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
  labelContainerInner: {
    flex: 1,
    paddingVertical: 10,
  },
  labelFormInner: {
    fontSize: 14,
    color: '#4b4b4b',
    paddingVertical: 5,
    paddingHorizontal: 10,
    fontWeight: '700',
    //fontFamily:fontLight
  },
  formInputInner: {
    width: '100%',
    height: 45,
    fontSize: 14,
    color: '#2d2d2f',
    backgroundColor: '#FFF',
    borderRadius: 5,
    paddingHorizontal: 10,
    //textAlignVertical:"top"
    //fontFamily:fontRegular
  },
  formInputInnerText: {
    width: '100%',
    lineHeight: 45,
    fontSize: 16,
    color: '#2d2d2f',
    backgroundColor: '#FFF',
    borderRadius: 10,
    paddingHorizontal: 10,
    //fontFamily:fontRegular
  },
  checkinText: {
    fontSize: fontMedium,
    color: '#73879b',
    paddingVertical: 5,
    textAlign: 'center',
  },
  payText: {
    textAlign: 'center',
    flex: 1,
    color: '#030505',
    fontWeight: 'bold',
    fontSize: fontMedium,
    paddingVertical: 2,
  },
  payTextDesc: {
    textAlign: 'center',
    flex: 1,
    color: '#73879b',
    fontSize: fontSmall,
    paddingTop: 5,
    paddingBottom: 10,
    lineHeight: 23,
  },
  payTextAmount: {
    textAlign: 'center',
    flex: 1,
    color: '#f27f55',
    fontSize: fontXLarge,
    paddingVertical: 2,
    fontWeight: 'bold',
  },
  barHeaderButtons: {
    flex: 1,
    height: 45,
    backgroundColor: '#15dbdf',
    justifyContent: 'center',
    alignItems: 'center',
  },
  barHeaderButtonsUnselected: {
    flex: 1,
    height: 45,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  barheaderText: {
    color: '#d4d4d4',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  barHeaderTextUnselected: {
    color: '#FFF',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  gymItemContainer: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    backgroundColor: whiteColor,
    marginVertical: 10,
    borderWidth: 0.8,
    borderColor: '#e0dede',
  },
  searchItemContainer: {
    flex: 1,
    paddingTop: 20,
    borderBottomWidth: 0.5,
    borderColor: '#c7c7c7',
    paddingBottom: 15,
  },
  insuranceContainer: {
    flex: 1,
    borderRadius: 10,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    backgroundColor: whiteColor,
    marginVertical: 10,
    borderWidth: 0.8,
    borderColor: '#e0dede',
    elevation: 1,
  },
  gymIconContInner: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#707070',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 5,
    shadowOpacity: 0.2,
    borderWidth: Platform.OS == 'ios' ? 0 : 0.2,
    borderColor: '#a5a4a4',
    elevation: 4,
  },
  gymIconImage: {
    width: 45,
    height: 45,
    resizeMode: 'contain',
  },
  gymIconCont: {
    width: 50,
    margin: 10,
  },
  gymListHeading: {
    color: '#4b4b4b',
    fontSize: 15,
    fontFamily: fontSemiBold,
    paddingVertical: 3,
  },
  gymListDesc: {
    color: '#787878',
    fontSize: 12,
    //fontFamily: fontRegular,
    lineHeight: 20,
  },
  gymImageContInner: {
    width: 100,
    height: 100,
    overflow: 'hidden',
    borderRadius: 10,
    top: -20,
    backgroundColor: 'grey',
    borderWidth: 0.3,
    borderColor: '#a5a4a4',
  },
  gymImage: {
    width: 100,
    height: 100,
    resizeMode: 'cover',
  },
  gymImageCont: {
    width: 100,
  },
  notItemContainer: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 7,
    backgroundColor: whiteColor,
    marginVertical: 5,
    borderWidth: 0.8,
    borderColor: '#e0dede',
  },
  notIconCont: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subHeaderButtons: {
    flex: 1,
    height: 45,
    backgroundColor: whiteColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: '#e7e8e8',
    paddingBottom: 10,
    marginBottom: 5,
  },
  subHeaderButtonsUnselected: {
    flex: 1,
    height: 45,
    backgroundColor: whiteColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderColor: '#000',
    paddingBottom: 10,
    marginBottom: 5,
  },
  subHeaderText: {
    color: '#000',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  subHeaderTextUnselected: {
    color: 'grey',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  starIconsBig: {
    fontSize: 30,
    marginHorizontal: 2,
    color: '#f3b118',
  },
  switchButton: {
    transform: [{ scaleX: 0.7 }, { scaleY: 0.7 }],
    resizeMode: 'contain',
  },
  mainMenu: {
    width: '100%',
    flexDirection: 'row',
    top: -40,
    zIndex: 999,
  },
  dashboardIcons: {
    width: width / 3,
    height: width / 3,
    resizeMode: 'contain',
  },
  dashInnerView: {
    width: width / 3,
    top: -20,
  },
  dashboardMainText: {
    fontSize: 14,
    color: '#4b4b4b',
    textAlign: 'center',
    //fontFamily: fontBold
  },
  dashboardInnerText: {
    fontSize: 12,
    color: '#a8a8a8',
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    //fontFamily: fontRegular
  },
  notItemContainer: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 15,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    backgroundColor: whiteColor,
    marginVertical: 10,
    borderWidth: 0.8,
    borderColor: '#e0dede',
  },
  notIconContInner: {
    width: 40,
    height: 40,
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: '#00d3db',
    borderWidth: 0.8,
    borderColor: '#00d3db',
  },
  notIconImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  notIconCont: {
    width: 40,
    alignItems: 'center',
  },
  editLabelContainer: {
    flexDirection: 'row',
    flex: 1,
    paddingVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 15,
    marginBottom: 15,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    backgroundColor: whiteColor,
    borderWidth: 0.8,
    borderColor: '#e0dede',
  },
  checkinHospitalName: {
    color: '#4b4b4b',
    textAlign: 'center',
    fontSize: 18,
    //fontFamily: fontBolder,
    paddingTop: 5,
  },
  checkinHospitalText: {
    color: '#808386',
    textAlign: 'center',
    fontSize: 11,
    //fontFamily: fontBold,
    paddingVertical: 5,
  },
  checkinHospitalAdd: {
    color: '#a8a8a8',
    textAlign: 'center',
    fontSize: 14,
    //fontFamily: fontRegular,
    paddingVertical: 5,
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  appIconContInner: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#109EC2',
  },
  appIconImage: {
    width: 80,
    height: 80,
    resizeMode: 'cover',
    borderWidth: 0.8,
    borderRadius: 8,
    borderColor: '#00d3db',
  },
  appIconCont: {
    width: 80,
  },
  appListHeading: {
    color: '#4b4b4b',
    fontSize: 15,
    //fontFamily: fontBold,
    paddingTop: 16,
    paddingBottom: 5,
  },
  popupLabelContainer: {
    width: '100%',
    flexDirection: 'row',
    paddingVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 15,
    marginBottom: 15,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    backgroundColor: whiteColor,
    borderWidth: 0.8,
    borderColor: '#e0dede',
  },
  filterLabel: {
    color: '#8290AF',
    fontSize: 16,
    fontWeight: '600',
    paddingTop: 5,
  },
  filterInputText: {
    fontSize: 14,
    color: '#1D2733',
    //fontFamily:fontRegular,
    paddingVertical: 15,
    fontWeight: '500',
    width: '75%',
    paddingLeft: 10,
  },
  emptyListStyle: {
    flex: 1,
    justifyContent: 'center',
  },
  emptyMessageStyle: {
    textAlign: 'center',
    color: '#4b4b4b',
    fontSize: 15,
    //fontFamily: fontBold,
  },
  searchRow: {
    height: 60,
    flexDirection: 'row',
    borderColor: '#50800a',
    borderWidth: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  inputStyles: {
    color: '#1D2733',
    fontWeight: '500',
    fontSize: 14,
    backgroundColor: 'transparent',
    height: 50,
    width: width - 20,
    paddingHorizontal: 15,
  },
  cancelButton: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 20,
    zIndex: 999,
    backgroundColor: '#50800a',
  },
  canceText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  searchheader: {
    width: 100,
    backgroundColor: '#50800a',
    height: 120,
    justifyContent: 'center',
  },
  map: {
    width: width,
    height: height - 90,
  },
  logoBg: {
    width: width,
    resizeMode: 'stretch',
    height: 300,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    overflow: 'hidden',
  },
  logoBg1: {
    width: width,
    resizeMode: 'stretch',
    height: Platform.OS == 'ios' ? 260 : 240,
  },
  logoBg2: {
    width: width,
    resizeMode: 'stretch',
    height: Platform.OS == 'ios' ? 120 : 100,
  },
  logoBg3: {
    width: width,
    resizeMode: 'stretch',
    height: 180,
  },
  imageBg2: { width: width, height: 350, resizeMode: 'cover' },
  logo: {
    width: width / 2.5,
    height: 200,
    alignSelf: 'center',
    resizeMode: 'contain',
    top: -40,
  },
  formContainer: {
    flex: 1,
    width: '94%',
    marginHorizontal: '3%',
    backgroundColor: '#FFF',
    borderRadius: 20,
    top: -50,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#F9F9FC',
  },

  formContainer2: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F9F9FC',
    borderRadius: 20,
    top: -20,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#F9F9FC',
  },
  bookingCard: {
    borderRadius: 10,
    marginTop: '2%',
    borderWidth: 1,
    alignSelf: 'center',
    width: '95%',
    // height: '52%',
    padding: 20,
    height: 'auto',
    borderColor: '#F9F9FC',
    backgroundColor: '#FFF',
  },
  txt: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'grey',
    marginTop: '3%',
  },
  txtTwo: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: '3%',
    marginRight: 5,
  },

  txtThree: {
    color: 'blue',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: '3%',
    right: 0,
    flexGrow: 1,
    flexBasis: 0,
  },
  iconStyle: {
    width: 20,
    height: 20,
    fontSize: 14,
    color: '#787878',
    marginVertical: 2,
    marginTop: '5%',
  },
  cardTxt: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  cardTxtTwo: {
    flexDirection: 'row',
    width: '60%',
  },
  cardTwo: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  txtDate: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: '3%',
    color: 'grey',
    paddingLeft: '22%',
  },
  devider: {
    marginTop: 20,
  },
  btnView: {
    marginTop: '5%',
    marginBottom: '2%',
    flexDirection: 'row',
    height: '20%',
    justifyContent: 'space-between',
  },
  btnIgnore: {
    width: '30%',
    maxHeight: '60%',
    backgroundColor: '#FF0000',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnAccept: {
    width: '30%',
    maxHeight: '60%',
    backgroundColor: '#5440D7',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnV: {
    width: '30%',
    maxHeight: '60%',
    borderWidth: 1,
    borderColor: '#5440D7',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnTxt: {
    alignSelf: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  btnTxtView: {
    alignSelf: 'center',
    justifyContent: 'center',
    color: '#5440D7',
    fontSize: 14,
    fontWeight: 'bold',
  },
  content: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: Constants.fontSemiBold,
    paddingTop: 20,
  },
  contentDesc: {
    color: '#FFF',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: Constants.fontRegular,
    paddingVertical: 10,
    paddingHorizontal: 50,
  },
  searchBar: {
    width: '80%',
    height: '20%',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 10,
    flexDirection: 'row',
  },
  phoneText: {
    height: 50,
    fontSize: 16,
    color: '#000000',
  },
  formInput: {
    width: '100%',
    height: 50,
    fontSize: 16,
    color: '#000000',
  },
  loginButtonWrapper: {
    width: '100%',
    paddingVertical: 20,
  },
  logoButton: {
    width: '100%',
    height: 50,
    resizeMode: 'contain',
  },
  imageStyles: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#F9F9FC',
  },
  textInput: {
    flex: 1,
    height: 45,
    color: '#000',
    paddingHorizontal: 10,
    fontSize: 15,
  },
  textInputText: {
    flex: 1,
    color: '#000',
    paddingHorizontal: 10,
    fontSize: 15,
  },
  shadowBox: {
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 10,
    shadowColor: '#a5a4a4',
    shadowOffset: { width: 1, height: 3 },
    shadowRadius: 3,
    shadowOpacity: 0.3,
    paddingVertical: 10,
    borderWidth: Platform.OS == 'ios' ? 0 : 0.2,
    borderColor: '#a5a4a4',
    elevation: 4,
    marginVertical: 5,
  },
  reviewModal: {
    width: width - 80,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingTop: 20,
    paddingHorizontal: 20,
    left: leftPopup / 2,
  },
  reviewModal2: {
    width: width - 40,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  reviewModalTitle: {
    fontSize: 18,
    paddingTop: 20,
    textAlign: 'center',
    fontFamily: fontBold,
  },
  textArea: {
    // alignItems:'center',
    padding: 10,
    borderWidth: 0.4,
    borderColor: '#ccc',
    marginVertical: 12,
    backgroundColor: '#F9F9FC',
    borderRadius: 9,
    paddingVertical: 10,
    // paddingHorizontal:17,
  },
  headerIcons: {
    fontSize: 20,
    paddingTop: 15,
    color: '#FFF',
    width: 40,
    textAlign: 'center',
  },
  backButtonIcon: {
    fontSize: 26,
  },
});

export default styles;
