const Images = {
    bg_splash: require('../assets/bg_splash.png'),
    loginHeaderBg: require('../assets/loginHeaderBg.png'),
    registerHeaderBg: require('../assets/registerHeaderBg.png'),
    splashLogo: require('../assets/splashLogo.png'),
    logo: require('../assets/Logo.png'),
    header_with_white_bg: require('../assets/bg_header_white.png'),
    icon_checkbox_unselected: require('../assets/icon_checkbox_unselected.png'),
    icon_checkbox_selected: require('../assets/icon_checkbox_selected.png'),
    back: require('../assets/back.png'),
    bg_short_bg_header: require('../assets/bg_short_bg_header.png'),
    icon_agree_red: require('../assets/icon_agree_red.png'),
    icon_disagree: require('../assets/icon_disagree_hover.png'),
    icon_sidemenu_change_password: require('../assets/icon_sidemenu_change_password.png'),
    icon_sidemenu_about_us: require('../assets/icon_sidemenu_about_us.png'),
    icon_sidemenu_about_us: require('../assets/icon_sidemenu_about_us.png'),
    icon_sidemenu_contact_us: require('../assets/icon_sidemenu_contact_us.png'),
    icon_sidemenu_notification: require('../assets/icon_sidemenu_notification.png'),
    icon_sidemenu_other_apps: require('../assets/icon_sidemenu_other_apps.png'),
    icon_sidemenu_other_apps: require('../assets/icon_sidemenu_other_apps.png'),
    icon_sidemenu_payment: require('../assets/icon_sidemenu_payment.png'),
    icon_sidemenu_phone_resgistration: require('../assets/icon_sidemenu_phone_resgistration.png'),
    icon_sidemenu_terms_condition: require('../assets/icon_sidemenu_terms_condition.png'),
    icon_sidemenu_subscription: require('../assets/icon_sidemenu_subscription.png'),
    icon_search : require('../assets/iconSearch.png'),
    splash_loading : require('../assets/Loader.gif'),
    CalendarDD: require('../assets/calendarDropDown.png'),
    Howtouse: require('../assets/howtouse.png'),
    LoginBg: require('../assets/loginBg.png'),
    WhatsappButton: require('../assets/whatsAppButton.png'),
    PhoneCallButton: require('../assets/phoneCallButton.png'),
    DashboardBg: require('../assets/dashboardBg.png'),
    BookingList: require('../assets/bookingList.png'),
    CleaningPicture: require('../assets/cleaningPicture.png'),
    CleaningDetails: require('../assets/cleaningDetails.png'),
    ReviewsText: require('../assets/reviewsText.png'),
    MapImage: require('../assets/mapImage.png'),
    ServiceItem: require('../assets/serviceItem.png'),
    Thanks: require('../assets/thanks.png'),
    Catimage1: require('../assets/catimage1.png'),
    Catimage2: require('../assets/catimage2.png'),
    Catimage3: require('../assets/catimage3.png'),
    CameraIcon: require('../assets/cameraIcon.png'),
    drawer_logo: require('../assets/drawer_logo.png')
}

export default Images;
